services:
  discordbot:
    build: .
    container_name: discordbot
    restart: unless-stopped
    environment:
      CONNECTION_STRING: ${CONNECTION_STRING}
      HETZNER_API_KEY: ${HETZNER_API_KEY}
      SECRET_KEY: ${SECRET_KEY}
      OPENAI_KEY: ${OPENAI_KEY}
    networks:
      - internal-db
    volumes:
      - ./data:/app/data

networks:
  internal-db:
    external: true
    name: ${MONGO_NETWORK:-mongodb_internal-db}
